# syntax=docker/dockerfile:1
FROM python:3

RUN apt-get update && apt-get install -y \
    iputils-ping \
    net-tools \
    iproute2 \
    tcpdump

WORKDIR /usr/src/app

COPY . .

CMD [ "sh", "-c", "python3 client.py -h ${host} -p ${port} -rmaddr ${rmaddr}" ]
