version: "3"

services:
  bmv2:
    image: p4switch-new-l2:latest
    hostname: bmv2-l2
    container_name: bmv2-l2
    privileged: true
    tty: true
    stdin_open: true
    volumes:
      - ./tmp:/tmp
      - /home/rodrigo/bmv2_config/basic.json:/behavioral-model/basic.json
      - /home/rodrigo/bmv2_config/p4info.txt:/behavioral-model/p4info.txt
    networks:
      test_cl:
        ipv4_address: 10.31.0.5
      test_srv:
        ipv4_address: 10.30.0.5
      test_switch:
        ipv4_address: 10.32.0.5
      test_kube:
        ipv4_address: 10.33.0.5
    command: bash -c "ip a del 10.31.0.5 dev eth0 && ip a del 10.30.0.5 dev eth2 && simple_switch_grpc -i 1@eth2 -i 2@eth0 -i 3@eth1 /behavioral-model/basic.json --device-id 1 --debugger --log-level debug --log-file logs"
  
  exposureManagmentFunction:
    image: expmngmtfn:v1
    hostname: expmngmtfn
    container_name: expmngmtfn
    privileged : true
    tty: true
    stdin_open: true
    ports:
      - "8000:8000/tcp"
    networks:
      test_srv:
        ipv4_address: 10.30.0.50
      test_switch:
        ipv4_address: 10.32.0.50
    command: bash -c "uvicorn ExposureManagmentFunction:app --reload --host 10.30.0.50"
    depends_on:
      - bmv2
  
  p4RuntimeController:
    image: p4netcontroller:v1
    hostname: p4netcontroller
    container_name: p4netcontroller
    privileged : true
    tty: true
    stdin_open: true
    volumes:
      - /home/rodrigo/bmv2_config/p4info.txt:/usr/src/app/p4info.txt
      - /home/rodrigo/bmv2_config/basic.json:/usr/src/app/basic.json
    command: bash -c "python3 p4switchController.py --p4info /usr/src/app/p4info.txt --bmv2-json /usr/src/app/basic.json"
    networks:
      test_srv:
        ipv4_address: 10.30.0.10
      test_switch:
        ipv4_address: 10.32.0.10
    depends_on:
      - bmv2
      - exposureManagmentFunction
  
  computationController:
    image: computationcontroller:v1
    hostname: computationController
    container_name: computationController
    privileged : true
    tty: true
    stdin_open: true
    ports:
      - "80:80/tcp"
    command: bash -c "ping -c 1 10.0.2.15 && python3 kubeController.py"
    networks:
      test_srv:
        ipv4_address: 10.30.0.20
      test_switch:
        ipv4_address: 10.32.0.20
    depends_on:
      - bmv2
      - exposureManagmentFunction
      
  server:
    image: server-clientlike-l2:latest
    hostname: server-basic-l2
    container_name: server-clientlike-l2
    privileged: true
    ports:
      - "5000:5000/udp"
    volumes:
      - ./tmp/server:/tmp
    environment:
      - host=10.30.0.30
      - port=5001
      - mode=rightaway
      - rmaddr=10.31.0.30
    networks:
      test_srv:
        ipv4_address: 10.30.0.30
    command: bash -c "ip r del default via 10.30.0.1 && ip r add default via 10.30.0.5 && arp -s 10.30.0.5 02:42:0a:1e:00:05 && python3 server.py -h $${host} -p $${port} -m $${mode} -rmaddr $${rmaddr}"
    depends_on:
      - bmv2
      - p4RuntimeController
      - computationController

  client:
    image: client-basic-l2:latest
    hostname: client-basic-l2
    container_name: client-basic-l2
    privileged: true
    ports:
      - "5001:5001/udp"
    volumes:
      - ./tmp/client:/tmp
    environment:
      - host=10.31.0.30
      - port=5000
      - rmaddr=10.30.0.30
    networks:
      test_cl:
        ipv4_address: 10.31.0.30
    command: bash -c "ip r del default via 10.31.0.1 && ip r add default via 10.31.0.5 && arp -s 10.31.0.5 02:42:0a:1f:00:05 && python3 client.py -h $${host} -rmaddr $${rmaddr} -p $${port}"
    depends_on:
      - bmv2
      - p4RuntimeController
      - computationController

networks:
  test_srv:
    name: test_srv
    external: true
  test_cl:
    name: test_cl
    external: true
  test_kube:
    name: test_kube
    external: true
  test_switch:
    name: test_switch
    external: true


