# syntax=docker/dockerfile:1
FROM python:3

RUN apt-get update && apt-get install -y \
    iputils-ping \
    net-tools \
    iproute2 \
    tcpdump

RUN pip3 install requests

WORKDIR /usr/src/app

COPY . .

CMD [ "sh", "-c", "python3 server.py -h ${host} -p ${port}" ]
